---
development:
  cloud_name: dvtmg0qwc
  api_key: '579211759547231'
  api_secret: JmBc-fSOM2gOteidjxNGdcgKh78
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dvtmg0qwc
  api_key: '579211759547231'
  api_secret: JmBc-fSOM2gOteidjxNGdcgKh78
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dvtmg0qwc
  api_key: '579211759547231'
  api_secret: JmBc-fSOM2gOteidjxNGdcgKh78
  enhance_image_tag: true
  static_image_support: false
